// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eToursSystem.Entities;

public partial class Destination
{
    [Key]
    public int DestinationID { get; set; }

    [Required(ErrorMessage = "Location is required. Cannot be blank.")]
    [StringLength(100, ErrorMessage ="Location is limited to 100 characters.")]
    public string Location { get; set; }

    [StringLength(30, ErrorMessage = "Country is limited to 30 characters.")]
    public string Country { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime VisitDate { get; set; }

    public double? StayDuration { get; set; }

    public int TourID { get; set; }

    [ForeignKey("TourID")]
    [InverseProperty("Destinations")]
    public virtual Tour Tour { get; set; }
}