// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eToursSystem.Entities;

public partial class Tour
{
    [Key]
    public int TourID { get; set; }

    [Required]
    [StringLength(125)]
    public string Name { get; set; }

    public int TourTypeID { get; set; }

    public int TransportID { get; set; }

    public int TripDuration { get; set; }

    [InverseProperty("Tour")]
    public virtual ICollection<Destination> Destinations { get; set; } = new List<Destination>();

    [ForeignKey("TourTypeID")]
    [InverseProperty("Tours")]
    public virtual TourType TourType { get; set; }

    [ForeignKey("TransportID")]
    [InverseProperty("Tours")]
    public virtual Transport Transport { get; set; }
}