// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eToursSystem.Entities;

public partial class TourType
{
    [Key]
    public int TourTypeID { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [InverseProperty("TourType")]
    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}