// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eToursSystem.Entities;

public partial class Transport
{
    [Key]
    public int TransportID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int Capacity { get; set; }

    [Required]
    [StringLength(1)]
    public string LandWaterRiver { get; set; }

    [InverseProperty("Transport")]
    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}