// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using eToursSystem.Entities;

namespace eToursSystem.DAL;

internal partial class eToursContext : DbContext
{
    public eToursContext(DbContextOptions<eToursContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Destination> Destinations { get; set; }

    public virtual DbSet<Tour> Tours { get; set; }

    public virtual DbSet<TourType> TourTypes { get; set; }

    public virtual DbSet<Transport> Transports { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Destination>(entity =>
        {
            entity.HasKey(e => e.DestinationID).HasName("PK_Destinations_DestinationID");

            entity.HasOne(d => d.Tour).WithMany(p => p.Destinations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DestinationsTours_TourID");
        });

        modelBuilder.Entity<Tour>(entity =>
        {
            entity.HasKey(e => e.TourID).HasName("PK_Tours_TourID");

            entity.HasOne(d => d.TourType).WithMany(p => p.Tours)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ToursTourTypes_TourTypeID");

            entity.HasOne(d => d.Transport).WithMany(p => p.Tours)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ToursTransports_TransportID");
        });

        modelBuilder.Entity<TourType>(entity =>
        {
            entity.HasKey(e => e.TourTypeID).HasName("PK_TourTypes_TourTypeID");
        });

        modelBuilder.Entity<Transport>(entity =>
        {
            entity.HasKey(e => e.TransportID).HasName("PK_Transport_TransportID");

            entity.Property(e => e.LandWaterRiver).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}